
##端口号
server:
  port: 8089
#  context-path:/mmall
use-forward-headers: true

#其它设置是让Tomcat去Http头信息去获取协议信息，而不是从HttpServletRequest
tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: X-Forwarded-Port

#配置数据库连接池
spring:
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource

    #druid相关配置
    druid:
    #监控统计拦截的filters
    filters: stat
    driver-class-name: com.mysql.jdbc.Driver

    #基本属性
    username: root
    password: 17B92f93756a
    url: jdbc:mysql://4xxxxxxxxx3:3306/xxxxx?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    username: root
#    password: asdq7558690
#    url: jdbc:mysql://localhost:3306/mmall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

    #配置初始化大小/最小/最大
    initial-size: 1
    min-idle: 1
    max-active: 20
    #获取连接等待超时时间
    max-wait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    time-between-eviction-runs-millis: 60000
    #一个连接在池中最小生存的时间
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20

  #rabbitmq
  rabbitmq:
    host: xxxxxx
    port: xxx
#    username: guest
    username: xx
    password: xx
    listener:
      concurrency: 10   #并发消费者的初始化值
      max-concurrency: 20   #并发消费者的最大值
      prefetch: 5     #每个消费者每次监听时可拉取处理的消息数量


  #邮箱配置
  mail:
    port: 465
    host: smtp.qq.com             # 设置邮箱主机
    username: xxxxxxxx@qq.com    # 设置用户名
    password: xxxx    # 设置密码，该处的密码是QQ邮箱开启SMTP的授权码而非QQ密码
    default-encoding: utf-8
    properties:
      mail.smtp.auth: true        # 设置是否需要认证，如果为true,那么用户名和密码就必须的，
      mail.smtp.starttls.required: true
      mail.smtp.starttls.enable: true # STARTTLS[1]  是对纯文本通信协议的扩展。它提供一种方式将纯文本连接升级为加密连接（TLS或SSL），而不是另外使用一个端口作加密通信
      sslClass: javax.net.ssl.SSLSocketFactory
    subject: 这是测试邮箱发送功能！！

# redis配置，以下有默认配置的也可以使用默认配置
redis:
  database: 0
  host: xxxxx3
  password: xxx
  port: xxxx
  timeout: 5000
  jedis:
    pool:
      max-active: 100
      max-wait: 5000

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.example.mmall.model

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 1800 #JWT的超期限时间(60*30)
  tokenHead: Bearer  #JWT负载中拿到开头

logging:
  level:
     com.example.mmall.mapper : info
